[package]
name = "tscompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# swc = "0.24"
swc_common = {version = "0.14", features=["sourcemap"]}
# swc_ecma_parser = "0.60"
swc_ecmascript = {version = "0.89.0", features=["codegen", "parser", "transforms", "typescript", "visit", "compat"]}
sourcemap = "6.0"